"""Composable preprocessing pipeline for downloaded remote-sensing products."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from common.config import load_config
from preprocessing.cloud_masks import (
    TorchCloudSegmenter,
    generate_threshold_mask,
    run_fmask,
)
from preprocessing.geospatial import (
    align_to_reference,
    clip_to_aoi,
    generate_patches,
    normalize_raster,
    reproject_raster,
)


@dataclass(slots=True)
class ScenePreprocessingResult:
    """Paths generated by preprocessing a scene."""

    normalized_path: Path
    mask_path: Path
    patch_paths: list[Path]


class PreprocessingPipeline:
    """Run reprojection, clipping, normalization, cloud masks, and patch generation."""

    def __init__(self, config_path: str | Path = "config/default.yaml") -> None:
        """Load preprocessing settings from YAML."""
        self.config = load_config(config_path)
        self.data_config = self.config["data"]

    def process_liss4_scene(self, input_path: str | Path, output_group: str) -> ScenePreprocessingResult:
        """Preprocess one LISS-IV scene into normalized products and patches."""
        raw = Path(input_path)
        processed_root = Path(self.data_config["processed_dir"]) / output_group
        reprojected = processed_root / "reprojected" / raw.name
        clipped = processed_root / "clipped" / raw.name
        normalized = processed_root / "normalized" / raw.name
        mask = Path(self.data_config["processed_dir"]) / "cloud_mask" / raw.name
        reproject_raster(raw, reprojected, self.data_config["output_crs"])
        clip_to_aoi(reprojected, self.data_config["aoi_path"], clipped)
        normalize_raster(clipped, normalized, nodata=self.data_config.get("nodata"))
        self._generate_cloud_mask(normalized, mask)
        patches = generate_patches(
            normalized,
            Path(self.data_config["patch_dir"]) / output_group,
            patch_size=int(self.data_config["patch_size"]),
            stride=int(self.data_config["stride"]),
            nodata=self.data_config.get("nodata"),
        )
        return ScenePreprocessingResult(normalized_path=normalized, mask_path=mask, patch_paths=patches)

    def _generate_cloud_mask(self, normalized_path: Path, mask_path: Path) -> None:
        """Generate a cloud mask using the configured strategy."""
        mask_config = self.config.get("cloud_mask", {})
        method = str(mask_config.get("method", "threshold")).lower()
        if method == "fmask":
            executable = str(mask_config.get("fmask", {}).get("executable", "fmask"))
            run_fmask(normalized_path, mask_path, executable=executable)
            return
        if method == "deep":
            checkpoint = mask_config.get("deep", {}).get("checkpoint")
            if not checkpoint:
                raise ValueError("Deep cloud mask requires cloud_mask.deep.checkpoint in config.")
            TorchCloudSegmenter(checkpoint).predict_file(normalized_path, mask_path)
            return
        threshold_config = mask_config.get("threshold", {})
        generate_threshold_mask(
            normalized_path,
            mask_path,
            visible_bands=threshold_config.get("visible_bands", (1, 2, 3)),
            brightness_quantile=float(threshold_config.get("brightness_quantile", 0.88)),
            min_component_pixels=int(threshold_config.get("min_component_pixels", 64)),
        )

    def align_auxiliary(self, auxiliary_paths: Iterable[str | Path], reference_path: str | Path, output_group: str) -> list[Path]:
        """Co-register auxiliary modalities to a processed LISS-IV reference grid."""
        outputs: list[Path] = []
        for path in auxiliary_paths:
            source = Path(path)
            aligned = Path(self.data_config["processed_dir"]) / output_group / source.name
            align_to_reference(source, reference_path, aligned)
            normalize_raster(aligned, aligned)
            outputs.append(aligned)
        return outputs
