name: uncloud-it
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - gdal
  - geopandas
  - rasterio
  - shapely
  - pyproj
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - pip:
      - -r requirements.txt
